### ISSUE TITLE
Must issue a STARTTLS command first

### ISSUE THREAD

**Issue by sentjurv** [serilog/serilog-sinks-email#102]
Hello,

I'm trying to configure serilog to send me emails:

                .WriteTo.Email(new EmailConnectionInfo
                {
                    FromEmail = "xxx@gmail.com",
                    ToEmail = "xxx@gmail.com",
                    MailServer = "smtp.gmail.com",
                    NetworkCredentials = new NetworkCredential
                    {
                        UserName = "xxx@gmail.com",
                        Password = "password"
                    },
                    EnableSsl = true,
                    Port = 587,
                    EmailSubject = "HRIS Integration Exception"
                }, restrictedToMinimumLevel: LogEventLevel.Error, batchPostingLimit: 1)
                
But have the followinf exception:
_The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.0 Must issue a STARTTLS command first._

Could you please advise?

**Comment by 0xced** [comment]
You would need to add `SecureSocketOption = SecureSocketOptions.StartTls` in the `EmailConnectionInfo` instance.

Note that this option is only available when targeting .NET Standard (1.3, 2.0 or 2.1) but not when targeting .NET Framework.

**Comment by prandoz** [comment]
Hi I try send mail with gmail, but without success. I don't understand where put SecureSocketOption  for StartTls. In my EmailConnectionInfo i can't put. I use the 2.4.0 version of Serilog.Skins.Email.
Thank you

**Comment by KieranDevvs** [comment]
> You would need to add `SecureSocketOption = SecureSocketOptions.StartTls` in the `EmailConnectionInfo` instance.
> 
> Note that this option is only available when targeting .NET Standard (1.3, 2.0 or 2.1) but not when targeting .NET Framework.
> 
> See also #96.

Why is this restricted to net standard and not core & .NET 5+?

**Comment by prandoz** [comment]
I resolved with Log.CloseAndFlush(); after log

**Comment by KieranDevvs** [comment]
I ended up just using `NLog`, they seem to support the `STARTTLS` protocol out of the box for .NET 6.

**Comment by nblumhardt** [comment]
3.0.0-dev on NuGet now enables `EmailConnectionInfo.SecureSocketOption` for all platforms. Any and all help testing/polishing that version appreciated.
