### ISSUE TITLE
Does this sink support expression templates?

### ISSUE THREAD

**Issue by cryo75** [serilog/serilog-sinks-email#114]
In my rolling file sink I have:

```csharp
"Formatter": {
  "Type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
  "Template": "{@t:yyyy-MM-dd HH:mm:ss.fff zzz} [{@l:u3}]{#if SourceContext is not null} ({Substring(SourceContext, LastIndexOf(SourceContext, '.') + 1)}){#end} {@m:lj}\n{@x}"
},
```

Can the above also be used with the email sink out of the box?

**Comment by nblumhardt** [comment]
Could be some problems for overload resolution - try the 3.0.0-dev versions of the package, and pass the `ExpressionTemplate` in code I think. The overloads of `WriteTo.Email` need some work.
