### ISSUE TITLE
Emails not sending

### ISSUE THREAD

**Issue by Shraned** [serilog/serilog-sinks-email#121]
Hello,

The emails are not sending .
Tried multiple code but still not sending .
Here part of my code : 

```csharp
public class Email_Logger : IEmail_Interface
{
    public Serilog.Core.Logger _email_Logger ;
    
    public Email_Logger()
    {
        _email_Logger = new LoggerConfiguration()
    .WriteTo.Email(new EmailConnectionInfo()
    {
        EmailSubject = "Subject Of Email",
        EnableSsl = false,
        FromEmail = "noreply@mondomain",
        MailServer = "FQDN of Internal SMTP SERVER",
        Port = 25,
        ToEmail = @"recipient@domain",
        NetworkCredentials=null,
        IsBodyHtml = true
    }
)
.CreateLogger();
}
```

Is there something wrong ?

**Comment by Michelh91** [comment]
What version of MailKit are you using? If you have Mailkit >2.6.0 it won't work.

Try donwgrading it to 2.6.0

Dont know why it has not been changed to make it work with newer versions of mailkit

**Comment by Shraned** [comment]
Hello

I'm not using MailKit...
Do u have a sample/tuto working ? 
Regards

**Comment by Michelh91** [comment]
Also, you might want to try enabling Serilog self debug to check if any error is raised internally:

`Serilog.Debugging.SelfLog.Enable(Console.Out);`

**Comment by Michelh91** [comment]
Office365 does't allow to send emails with the account password by default.

You have to have two factor enabled and then go to :

https://aka.ms/CreateAppPassword

And create an app password to send emails with that password.

If it's not working yet, try to call _email_interface.email_logger.CloseAndFlush(); after calling the logger.Error method to check if that triggers the email sending.

**Comment by Shraned** [comment]
ok for O365 but with my relay server it should work without credentials on port 25...
I Can't fing the _email_interface.email_logger.CloseAndFlush().

**Comment by Shraned** [comment]
hello it definitively doesn't work with .net7 and asp application... 
too bad.

**Comment by mohammadeunus** [comment]
Hi shraned, try changing the `new logconfiguration` to new `Serilog.LoggerConfiguration()`

**Comment by nblumhardt** [comment]
Hi! I've updated the version of MailKit we're using, and generally freshened up the package in the `3.0.0-dev-*` packages now on NuGet.

I have done very minimal testing, so the new dev packages may be broken in obvious ways, however there's a pretty good chance anything that was version-related will now be resolved.

Any help testing the new packages out would be appreciated; I'll close this as stale but please feel free to open a new issue with example configuration/source code if you still need help. Cheers!
