### ISSUE TITLE
How to set subject and body template in code when using batching

### ISSUE THREAD

**Issue by cmeeren** [serilog/serilog-sinks-email#127]
When using batching, I must specify an `EmailSinkOptions` in `WriteTo.Email`. Unlike the "loose" parameter overload of `WriteTo.Email`, `EmailSinkOptions.Body` and `EmailSinkOptions.Subject` are of type `ITextFormatter`. How can I set a simple string subject and body template when using batching, like I could pre-3.0?

**Comment by Randactyl** [comment]
`EmailSinkOptions` sets the default subject like this:
https://github.com/serilog/serilog-sinks-email/blob/ac58ea6161142e2ab4f22df3e863eb36104c0c53/src/Serilog.Sinks.Email/Sinks/Email/EmailSinkOptions.cs#L75

**Comment by cmeeren** [comment]
Thanks, works great!

**Comment by bartelink** [comment]
> Thanks, works great! Should be documented.

Yes, 'someone' should do that :P
