### ISSUE TITLE
How to configure appsetting.json for Email to use running account credentials

### ISSUE THREAD

**Issue by jlrouzies-mantu** [serilog/serilog-sinks-email#138]
Hello,

With NLog, it is relatively easy to use the current user / NTLM / Kerberos to do SMTP.

But I can't figure how to do that with Serilog in appsettings.json, any idea?

**Comment by bartelink** [comment]
Might be worth asking on SO too - these repos have low watcher counts and the issues are generally used for confirmed issues rathe than usage questions

**Comment by bartelink** [comment]
Closing as dup of https://github.com/serilog/serilog-sinks-email/issues/136#issue-2418848541

I submit the fact that the existing issue is open for 3 weeks with no answer as evidence that it's the better of two evils for these usage questions to live on SO

Hopefully someone can circle back and post a PR to add a usage sample at the point one has been figured out and verified
