### ISSUE TITLE
Serilog.FullNetFx error with ASP.NET Core1 RC1

### ISSUE THREAD

**Issue by BillMcCrary** [serilog/serilog-sinks-email#15]
Sirilog is playing pretty nicely with core1, my only real problem is wiring up the Email sink.  I get this error:

Could not load file or assembly 'Serilog.FullNetFx, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified.

**Comment by merbla** [comment]
Hi @BillMcCrary,

The email sink has not yet been reworked to align with DotNetCore.  Now that [2.0](https://github.com/serilog/serilog/issues?q=is%3Aissue+is%3Aopen+label%3Av2) of Serilog is getting closer the sinks will get some needed attention. If you feel comfortable a PR would be more than welcome.

**Comment by myccy8** [comment]
Why don't you use mailkit?

**Comment by adamchester** [comment]
Pending mailkit support in PR #19

**Comment by arielcloud** [comment]
@merbla why you not merge this PR? Thanks

**Comment by nblumhardt** [comment]
Now supported as https://www.nuget.org/packages/Serilog.Sinks.Email/2.1.0-dev-00046 - any feedback on how it goes would be great. Thanks @adamchester!
