### ISSUE TITLE
when will serilog.email.sink support .net core RC2

### ISSUE THREAD

**Issue by guyajun0** [serilog/serilog-sinks-email#17]
Hi, I often use serilog.email.sink lib to send email, It is very convenient for me. I like the lib very much. And I often use Serilog to record some messages when the application is running. It's amazing.
But I find the serilog.email.sink does not support .net core RC2 so far, May I ask you when the serilog.email.sink lib will support the .net core RC2? Thank you!

**Comment by merbla** [comment]
Hi @guyajun0, 
It is on the [list](https://github.com/serilog/serilog/issues/590#issuecomment-219180555) we are slowly working through.  As you can understand with so many sinks and the subtle changes between RC1/RC2 it takes a little time.

If you want to jump in and help out by creating a PR, that would be fantastic.

**Comment by guyajun0** [comment]
Thank you for your reply, Your picture shows you are handsome , Good job
