### ISSUE TITLE
Log Level in Subject

### ISSUE THREAD

**Issue by Thaoden** [serilog/serilog-sinks-email#20]
I'd like to include the log level in the subject line. Is this possible? 
If not, would it be possible to include a formatter to the subject configuration?

**Comment by nblumhardt** [comment]
Hi @Thaoden - it's not possible with the code as it stands today, though I can't see any reason we couldn't implement it as an "output template" executed against the first log event in the batch. Are you interested in giving this a shot as a PR? Happy to send some pointers if you need help getting started. Cheers!

**Comment by jeremycook** [comment]
I'd take pointers and a shot at a PR @nblumhardt

**Comment by lloydpowell88** [comment]
I've had a go at this @jeremycook if you'd like to have a look on my branch and contribute in anyway.

@nblumhardt I considered 2 approaches to this, either allowing the mail subject to be a template and using the formatter in EmailSink itself, or the approach that I have taken, where the subject line is similar to the message formatter and dealt with in the configuration extension. Happy to hear your opinion and advice on my pull request. Also, this is my first open source pull request so any pointers that will help me going forward would be appreciated. Thanks!

[https://github.com/serilog/serilog-sinks-email/pull/26](Pull Request)

**Comment by nblumhardt** [comment]
In with #26.
