### ISSUE TITLE
NetStandard support

### ISSUE THREAD

**Issue by melenaos** [serilog/serilog-sinks-email#21]
I tried to use the sink at a mvc core project but it failed. As I can see you are using MailKit that it's build to support .net core and thus it might not need many changes. I need this sink for my project and I can help to migrate it to NetStandard.

**Comment by adamchester** [comment]
Hi @melenaos would you be able to give the pre-release version a test, and let us know if it's working? https://www.nuget.org/packages/Serilog.Sinks.Email/2.1.0-dev-00046

**Comment by melenaos** [comment]
@adamchester  I can do that :) I will report any problems i encounter using it, thank you.

**Comment by melenaos** [comment]
Hi @adamchester, 
I initialized the serilog with two sinks, RollingFile and Email, I set all the mail settings in the same way I used in an mvc5 project and trigger logging events both information and error.
I saw the logs in the file but unfortunately I haven't received any mail with the logs.
Is there any internal logging to enable so I can see more information and maybe trace the error?

**Comment by adamchester** [comment]
@melenaos thanks for trying this out.
Please enable [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) and that might give us some more information.

**Comment by melenaos** [comment]
It shows the following error:
`2016-11-22T20:59:43.7592606Z Failed to send email: MailKit.ServiceNotConnectedException: The SmtpClient must be connected before you can authenticate.
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at Serilog.Sinks.Email.EmailSink.OpenConnectedSmtpClient()
   at Serilog.Sinks.Email.EmailSink.<EmitBatchAsync>d__8.MoveNext()`

I am using the following initialization code for the sink:
`new LoggerConfiguration()
.MinimumLevel.Debug()
.Enrich.FromLogContext()
.WriteTo.Email(
                      
toEmail: loggerConfig.GetValue<string>("Mail:MailTo"),
mailSubject: loggerConfig.GetValue<string>("Mail:MailSubject"),

 fromEmail: mailConfig.GetValue<string>("MailFrom"),
 mailServer: mailConfig.GetValue<string>("MailServer"),
networkCredential: ParseCred(mailConfig.GetValue<string>("MailCredentials"))
).CreateLogger();`

**Comment by adamchester** [comment]
@melenaos thanks for reporting this bug.

Can you try the new build from AppVeyor?

https://ci.appveyor.com/project/serilog/serilog-sinks-email/build/47/artifacts

**Comment by adamchester** [comment]
Now published to Nuget https://ci.appveyor.com/project/serilog/serilog-sinks-email/build/48#L127

**Comment by melenaos** [comment]
It's working now!
Thank you very much for your work on this sink!

**Comment by adamchester** [comment]
🎉

**Comment by nblumhardt** [comment]
:shipit: ?

**Comment by adamchester** [comment]
:shipit:

**Comment by nblumhardt** [comment]
Shipped in 2.1.
