### ISSUE TITLE
{Message} in email Subject.

### ISSUE THREAD

**Issue by Head-Strong** [serilog/serilog-sinks-email#24]
Hi Team,

I am using this template for email subject : [Test] [LOCAL] - {Message}. But message is not displaying. 

Could you please help me on this ?

**Comment by nblumhardt** [comment]
Hi, thanks for getting in touch. The subject is not currently a template. I think this would be a good improvement if anyone is interested in submitting a PR.

**Comment by lloydpowell88** [comment]
Hi @Head-Strong, this functionality is currently in a pull request going through code review so keep an eye on it, hopefully it'll be available soon :-)

**Comment by nblumhardt** [comment]
In with #26.
