### ISSUE TITLE
sample configuration in readme

### ISSUE THREAD

**Issue by tomdeleu** [serilog/serilog-sinks-email#25]
Isn't the readme wrong? Should be "toEmail" instead of "to" etc. no?

**Comment by adamchester** [comment]
@tomdeleu thanks for reporting this, it looks like a bug in the readme.

Any chance you could send a PR to fix? 👍

**Comment by merbla** [comment]
@adamchester both [lines](https://github.com/serilog/serilog-sinks-email/blob/dev/test/Serilog.Sinks.Email.Tests/EmailSinkTests.cs#L18-L19) needs some love.

**Comment by merbla** [comment]
Fixed in [dev](https://github.com/serilog/serilog-sinks-email/commit/9435eab1dc192dfdb5cf4cbbcd649c36134228db)

**Comment by adamchester** [comment]
Thanks @merbla and @tomdeleu !

**Comment by tomdeleu** [comment]
Oops, too late. (Sure, wanted to send a pull request, but wanted to double check before doing so)

Thanks for fixing @merbla !
