### ISSUE TITLE
Not able to send emails through Amazon SES

### ISSUE THREAD

**Issue by mdmoura** [serilog/serilog-sinks-email#30]
I am trying to use Email Sink on an ASP.NET Core 1.1 application with Amazon SES:

        loggerConfiguration
          .WriteTo.Email(
            new EmailConnectionInfo { 
              EmailSubject = "Log",
              EnableSsl = true,
              FromEmail = "myname@mydomain.com",
              MailServer = "email-smtp.eu-west-1.amazonaws.com",
              NetworkCredentials = new NetworkCredential("MySMTPUsername", "MySMTPPassword"),
              Port = 587,
              ToEmail = "myname@mydomain.com"
            },
            "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}",
            LogEventLevel.Information); 

When I log an information I do not receive it by email ...

On the same application I am using Mailkit to send emails through Amazon SES and I don't have any problems:

      using (SmtpClient client = new SmtpClient()) {

        client.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;

        client.Connect("email-smtp.eu-west-1.amazonaws.com", 587, SecureSocketOptions.StartTlsWhenAvailable);
        client.Authenticate("MySMTPUsername", "MySMTPPassword");

        await client.SendAsync(message);

        client.Disconnect(true);

      }

Am I missing something? Maybe: 

        client.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;

**Comment by adamchester** [comment]
Hi @mdmoura! Thanks for reporting this issue.

Have you tried to [enable `SelfLog`](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) to help validate why the email sink can't write log messages?

Why does Amazon SES require you to disable server certificate validation? Is there any publicly documented reason?

**Comment by mdmoura** [comment]
I followed the answer of a MailKit issue:
https://github.com/jstedfast/MailKit/issues/421

Does this help in any way?

Tomorrow I will try the self log and provide more feedback if I find something else.

**Comment by adamchester** [comment]
@mdmoura - it does help. It would be great if you could provide the self log output. Thanks!

**Comment by mdmoura** [comment]
@adamchester Here it is the self log output:

2017-03-03T12:38:29.9753592Z Failed to send email: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.<>c.<ReadAsync>b__58_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at Serilog.Sinks.Email.EmailSink.OpenConnectedSmtpClient()
   at Serilog.Sinks.Email.EmailSink.<EmitBatchAsync>d__9.MoveNext()

Does this help?

**Comment by adamchester** [comment]
Hey @mdmoura can you try out https://www.nuget.org/packages/Serilog.Sinks.Email/2.2.1-dev-00067 and let know how it goes? We added `EmailConnectionInfo.ServerCertificateValidationCallback` in #31

**Comment by mdmoura** [comment]
@adamchester I tried:

        EmailConnectionInfo info = new EmailConnectionInfo {
          ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true
        };

But I get the compilation error:

    'The name 'ServerCertificateValidationCallback' does not exist in the current context

And: 

        EmailConnectionInfo info = new EmailConnectionInfo {
          DisableServerCertificateValidation = true
        };

But I get the compilation error:

    'EmailConnectionInfo' does not contain a definition for 'DisableServerCertificateValidation' 

I have this on ASP.NET Core 1.1 project with:

      <PropertyGroup>
          <TargetFramework>netcoreapp1.1</TargetFramework>
      </PropertyGroup>

      <PropertyGroup>
        <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
      </PropertyGroup>
       
I am also using MailKit 1.10.2 ...

What am I missing?

**Comment by adamchester** [comment]
I assume you got the wrong version of the package (needs `2.2.1-dev-00067`).

<img width="1184" alt="screen shot 2017-03-05 at 06 42 02" src="https://cloud.githubusercontent.com/assets/570470/23582119/f3ece4aa-016e-11e7-8d81-6add75c65dc0.png">

**Comment by mdmoura** [comment]
@adamchester I had the correct package version but somehow I need to delete the binary files and rebuild the application. The problem with sending the email using Amazon still persists. I am using the following:

    loggerConfiguration
      .WriteTo.Email(
        new EmailConnectionInfo { 
          EmailSubject = "Log",
          EnableSsl = true,
          FromEmail = "myname@mydomain.com",
          MailServer = "email-smtp.eu-west-1.amazonaws.com",
          NetworkCredentials = new NetworkCredential("MySMTPUsername", "MySMTPPassword"),
          Port = 587,
          ToEmail = "myname@mydomain.com",
          ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true
        },
        "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}",
        LogEventLevel.Information); 

But I get the following error when using the logger:      
      
2017-03-05T12:19:34.9314869Z Failed to send email: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.<>c.<ReadAsync>b__58_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at Serilog.Sinks.Email.EmailSink.OpenConnectedSmtpClient()
   at Serilog.Sinks.Email.EmailSink.<EmitBatchAsync>d__9.MoveNext()

I am also logging to the console and the message is displayed. I also have an email being send by MailKit directly and it is sent ..

Maybe something with SecureSocketOptions.StartTlsWhenAvailable?

**Comment by adamchester** [comment]
Hey @mdmoura I haven't had a chance to dig further here. Can you try experimenting with the MailKit settings that cause/prevent the issue you describe above?

**Comment by adamchester** [comment]
@mdmoura in your [console sample](https://github.com/serilog/serilog-sinks-email/pull/31#issuecomment-285666422), there is no [`async`](https://github.com/serilog/serilog-sinks-email/blob/745ce8757683ed585503af25e8045ab47eb91f42/src/Serilog.Sinks.Email/Sinks/Email/MailKitEmailSink.cs#L97) or call to [`SendAsync`](https://github.com/serilog/serilog-sinks-email/blob/745ce8757683ed585503af25e8045ab47eb91f42/src/Serilog.Sinks.Email/Sinks/Email/MailKitEmailSink.cs#L118). That could be the problem here; it might be that MailKit doesn't propagate the SSL or certificate information across the async call context (or that we're doing something prevent it?).

I'm still not sure what to do about it.

p.s. @nblumhardt can you reopen this issue please? I don't have permission (you could fix that too while you're there:))

**Comment by mdmoura** [comment]
@adamchester Not sure what you mean ... I am not using SendAsync in the console sample because, if I am not wrong, the Main method cannot be async. But the first part of the code, the one sending the email with Mailkit is working fine. However the Email Sink does not send the email when using logger.Information.

If the Mailkit works shouldn't the Logger Email Sink also work with the same configuration?

**Comment by adamchester** [comment]
@mdmoura Your console sample is not using async because it cannot be async; you are 100% right. 

My point is that could be the key difference between the two samples. That could be the reason why one works (console) and one doesn't (Logger).

The logger is async; the console example is not.

**Comment by mdmoura** [comment]
@adamchester Got it but in fact the original code is on an ASP.NET MVC core application and in that case everything is Async and the problem is the same ... I only used the Console application as an example to replicate the problem.

**Comment by adamchester** [comment]
@mdmoura so another possibility, we are using [serilog-sinks-periodicbatching](https://github.com/serilog/serilog-sinks-periodicbatching/blob/a9a90ce76634fc49ec3fd45bf417ff5977c52cfa/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L144). It does some interesting logic that could be the difference.

(note: i'm still not sure how to fix this, i'm just trying to throw out helpful comments that might help diagnose the issue)

**Comment by mdmoura** [comment]
@adamchester Maybe that is the problem but I also don't know how to fix it ... It would be nice that the Email Sink could use Amazon SES as it is a common email gateway.

**Comment by adamchester** [comment]
@mdmoura agreed, it should work. Thanks for reporting this and thanks for your efforts to help diagnose it.

**Comment by mdmoura** [comment]
@adamchester @nblumhardt Any news on this? Were you able to make the sink work with Amazon SES?

**Comment by adamchester** [comment]
@mdmoura there's no further progress here unfortunately. 😞 

If you were still waiting on this, anything new you can add might help push it along a little

**Comment by mdmoura** [comment]
@adamchester Unfortunately I wasn't able to solve this ... I have been reading Amazon Docs:
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html

I saw this code:

            var sesClient = new AmazonSimpleEmailServiceClient(new BasicAWSCredentials(_config.AwsAccessKeyId, _config.AwsSecretKey), new Amazon.SimpleEmail.AmazonSimpleEmailServiceConfig
            {
                RegionEndpoint = _config.RegionEndpoint,
                SignatureMethod = _config.SignatureMethod
            });

But until now I wasn't able to figure why Serilog Email sink isn't working with Amazon.

**Comment by dsoronda** [comment]
Any news on this ?

**Comment by mdmoura** [comment]
@dsoronda I wasn't able to make it work ... Will there be a solution with ASP.NET Core 2.0?

**Comment by nblumhardt** [comment]
Just a thought, perhaps a `Serilog.Sinks.AmazonSesEmail` would be a worthwhile direction to explore?

Guessing neither @adamchester nor I are using AWS SES currently, so ideally somebody who is will be able to figure this one out; not much chance of progress otherwise, unfortunately.

**Comment by nblumhardt** [comment]
Erm, like this one: https://www.nuget.org/packages/Serilog.Sinks.AmazonSimpleEmailService/

:-)

**Comment by dsoronda** [comment]
@nblumhardt , that [Amazon SES](https://www.nuget.org/packages/Serilog.Sinks.AmazonSimpleEmailService/) is old and doesn't work. It supports old Amazon SDK (not version 3). Also, it's missing support for .NET Core.

That's why I asked for update on this issue.

**Comment by evo-terren** [comment]
I just spent a little time on this and was able to get it to work. This is not intuitive at all, but you need to set `EnableSsl` to false, not true. When this parameter is passed off to the MailKit.MailService "Connect" method (see https://github.com/jstedfast/MailKit/blob/1.4.0/MailKit/MailService.cs#L569), you can see that this conditionally sets the SecureSocketOptions to either "SslOnConnect" (EnableSsl = true) or "StartTlsWhenAvailable" (EnableSsl = false). Clients of Amazon SES need "StartTlsWhenAvailable" because TLS is the only protocol supported.

Here are my final settings:
```
var awsConnectionInfo = new EmailConnectionInfo
{
    EnableSsl = false, //here's the important part
    FromEmail = "myfromname@mydomain.com",
    MailServer = "email-smtp.us-west-2.amazonaws.com",
    NetworkCredentials = new NetworkCredential("Username", "Password"),
    Port = 587,
    Subject = "Your Subject",
    ToEmail = "mytoname@mydomain.com"
};
Log.Logger = new LoggerConfiguration()
                    .WriteTo.Email(awsConnectionInfo);
```

Also, as mentioned in the above comments, you may want to set the `batchPostingLimit` to a number that you're expecting so that you don't get confused when the first email doesn't send due to batching.

I hope someone else is able to find this helpful!

**Comment by stevenrobertsvortextanalytics** [comment]
using this last value worked for me as well (using Outlook) but it seems that EnableSSL is no longer the best approach.  With ever evolving protocols etc, maybe having someway to pass in a protocol would be a good idea?  I realize I can always roll my own sink but maybe a protocol option in this base library would be good.
