### ISSUE TITLE
EmailConnectionInfo Has Its Own EmailSubject Property That is Ignored

### ISSUE THREAD

**Issue by jasel-lewis** [serilog/serilog-sinks-email#34]
Just curious why the following `LoggerConfiguration` extension accepts an email subject as its last parameter:

Email(EmailConnectionInfo connectionInfo, string outputTemplate, LogEventLevel restrictedToMinimumLevel, int batchPostingLimit, TimeSpan? period, IFormatProvider formatProvider, string mailSubject)

`EmailSubject` is a set-able member of an `EmailConnectionInfo` instance, which is expected as the first argument of the above extension method.  In fact, looking at the code, it appears as if the `EmailSubject` property is, effectively, ignored and only the `mailSubject` parameter passed to the extension method is used (or defaulted to `EmailConnectionInfo.DefaultSubject`) - which is not ideal.

I would expect that `EmailConnectionInfo.EmailSubject` is used within this extension method.  Am I missing something?

**Comment by jasel-lewis** [comment]
Please disregard.  I confused myself.  :P

**Comment by RafiHenig** [comment]
I'm having the same problam, what am I doing wrong?
