### ISSUE TITLE
Support lossy logging

### ISSUE THREAD

**Issue by cmeeren** [serilog/serilog-sinks-email#35]
log4net has this great feature where you can send an email when something is logged above a certain threshold, but that email then includes the last X messages above another threshold.

For example, I only want emails for warning and above, but when an email is sent, I'd like it to also contain the last several logging messages of any level to help with debugging. (Ideally i would like all messages for the current web request, but the last X messages would also work, and is what log4net does).

Is this currently possible? If not, would it be possible for you to implement this?

**Comment by nblumhardt** [comment]
Hi! No, there's no implementation at present, though a wrapper sink could be written to implement this in much the same way as log4net does 👍
