### ISSUE TITLE
Dynamic to address

### ISSUE THREAD

**Issue by itlackey** [serilog/serilog-sinks-email#36]
Is there any way to use a property of the event to determine the to address for this sink?

**Comment by nblumhardt** [comment]
Hi - are there a small, fixed, number of addresses? If so, https://github.com/serilog/serilog-sinks-map could be used for this. Any luck?

**Comment by itlackey** [comment]
I had not seen this before. Since trying to pull in a single address this looks like it may work. I will try to give it a shot tomorrow and report back.

Thanks!

**Comment by dbol55** [comment]
We are new to serilog, but really would like to have a solution for dynamic to addresses at somehow as a parameter.

**Comment by nblumhardt** [comment]
@dbol55 have you tried Serilog.Sinks.Map? Feedback on how it fits to your scenario would be useful. Thanks!

**Comment by dbol55** [comment]
Thank you for response. 
I might misunderstanded the comment a small, fixed number. 
I will check it out as one perhaps might could inject a dynamic email through this sink.
If you have a code example if would be appreciated 👍

**Comment by nblumhardt** [comment]
Closing this as stale, but still open to ideas around this.
