### ISSUE TITLE
LocalDomain property in MailKit

### ISSUE THREAD

**Issue by mnaiman** [serilog/serilog-sinks-email#38]
Hi, please add support to specify LocalDomain property of SmtpClient. Without that I'm unable to send email via my mail provider. Thx

**Comment by nblumhardt** [comment]
Thanks for the note 👍

This sounds like something that would be welcome, if anyone is able to look into it further and write up a PR.

**Comment by nblumhardt** [comment]
Closing this one as stale; thanks again!
