### ISSUE TITLE
Sending emails from UWP apps

### ISSUE THREAD

**Issue by Puiu** [serilog/serilog-sinks-email#41]
Hello,
I am trying to use the Email Sink in an UWP app, but I get this error when the app is trying to send the email:

> Exception thrown: 'System.IO.FileNotFoundException' in Serilog.Sinks.Email.dll
> 2017-08-02T11:25:23.7873916Z Failed to send email: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> File name: 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>    at Serilog.Sinks.Email.EmailSink.OpenConnectedSmtpClient()
>    at Serilog.Sinks.Email.EmailSink.<EmitBatchAsync>d__9.MoveNext()

I have added the reference to System.Net.Security (now version 4.3.1). I believe it is related to [this issue](https://github.com/dotnet/corefx/issues/19783)

Do you have any ideea how to solve this? Or maybe there is a workaround?

Alex

**Comment by nblumhardt** [comment]
Hi! From the linked issue, looks like the fix is coming in a future .NET Core release. No ideas otherwise, sorry.
