### ISSUE TITLE
Serilog Email sink is not sending emails

### ISSUE THREAD

**Issue by xantari** [serilog/serilog-sinks-email#44]
```
            Log.Logger = new LoggerConfiguration()
                .WriteTo.RollingFile(AppSettings.SerilogErrorLoggingFilePattern)
                .WriteTo.ColoredConsole()
                .WriteTo.Email(new EmailConnectionInfo()
                    {
                        FromEmail = AppSettings.ErrorEmailFrom,
                        EnableSsl = AppSettings.SmtpInfo.Network.EnableSsl,
                        EmailSubject = "FaxFormCreator Error",
                        IsBodyHtml = true,
                        MailServer = AppSettings.SmtpInfo.Network.Host,
                        NetworkCredentials = !(string.IsNullOrEmpty(AppSettings.SmtpInfo.Network.UserName)) ? new NetworkCredential(AppSettings.SmtpInfo.Network.UserName, AppSettings.SmtpInfo.Network.Password) : null,
                        Port = AppSettings.SmtpInfo.Network.Port,
                        ToEmail = AppSettings.ErrorOperatorEmail
                    },
                    restrictedToMinimumLevel: LogEventLevel.Information)
                .CreateLogger();
```

Using the above code, no email is ever sent. Works fine via regular SMTP .NET connection.

How to debug?

**Comment by xantari** [comment]
Also, I am running different log statements (Log.Information, Log.Error). But it doesn't send.

**Comment by fredjeck** [comment]
Hello, 
Email Sink is relying on the PeriodicBatching Sink which following its configuration buffers the logs and periodically (or when you hit the batchPostingLimit threshold) writes them to the sink.
That means that before your application is closing you have to explicitely flush your sinks (overall its a good practice) to trigger a write : just call the  `Log.CloseAndFlush();` method in a `finally` block
```C#
try{
    //Boring application code
}catch(Exception e){
    Log.Fatal(e, "Woops, something went wrong");
}finally{
    Log.CloseAndFlush();
}
```

**Comment by dougkwilson** [comment]
If an error is occurs while Serilog is attempting to send the email (due to a configuration issue, or error connecting to the server, etc.) then Serilog just swallows it.   If you want to see the error/exception you have to provide someplace for Serilog to dump it when you initialize logging:

```csharp
Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
```

or
```csharp
var selfLogMessages = new List<String>();
Serilog.Debugging.SelfLog.Enable(selfLogMessages.Add);
```

**Comment by Inrego** [comment]
Even when using `Log.CloseAndFlush()` there is some timing issues which means not all events are included in the e-mail. For example, this simple console application results in no e-mail being sent, even though I am writing 100 events to the log:

    static void Main(string[] args)
    {
        try
        {
            Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
            var emailInfo = new EmailConnectionInfo
            {
                EmailSubject = "Serilog Email Bug",
                EnableSsl = false,
                FromEmail = "info@knowhowdata.dk",
                MailServer = "smtp.dk",
                ToEmail = "rss@knowhowdata.dk",
                NetworkCredentials = new NetworkCredential("pa@knowhowdata.dk", "khd43424342")
            };

            var logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Email(emailInfo)
                .CreateLogger();

            for (var i = 1; i <= 100; i++)
            {
                logger.Information($"Log #{i}");
            }
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

**Comment by Inrego** [comment]
In the following case, no emails are sent at all, even with 100 events written to the log:

    static void Main(string[] args)
    {
        try
        {
            Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
            var emailInfo = new EmailConnectionInfo
            {
                EmailSubject = "Serilog Email Bug",
                EnableSsl = false,
                FromEmail = "fromEmail",
                MailServer = "smtpServer",
                ToEmail = "toEmail",
                NetworkCredentials = new NetworkCredential("username", "password")
            };

            var logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Email(emailInfo)
                .CreateLogger();

            for (var i = 1; i <= 100; i++)
            {
                logger.Information($"Log #{i}");
            }
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

**Comment by nblumhardt** [comment]
@Inrego for `Log.CloseAndFlush()` to work, you need to assign the shared `Log.Logger`; a `using` block will work otherwise:

```csharp
static void Main(string[] args)
{
    Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
    var emailInfo = new EmailConnectionInfo
        {
            EmailSubject = "Serilog Email Bug",
            EnableSsl = false,
            FromEmail = "fromEmail",
            MailServer = "smtpServer",
            ToEmail = "toEmail",
            NetworkCredentials = new NetworkCredential("username", "password")
        };

    using (var logger = new LoggerConfiguration()
            .MinimumLevel.Information()
            .WriteTo.Email(emailInfo)
            .CreateLogger())
    {
        for (var i = 1; i <= 100; i++)
        {
            logger.Information($"Log #{i}");
        }
    }
}
```

**Comment by Inrego** [comment]
Aha, that makes sense. Thank you!

**Comment by nblumhardt** [comment]
Closing this thread as it's diverged a bit :+1:

**Comment by djangohunt** [comment]
Using this example code, I still can't get the email sink to work. I don't see any errors or exceptions, I just don't receive any emails.
