### ISSUE TITLE
Anonymous Credentials

### ISSUE THREAD

**Issue by jamesSampica** [serilog/serilog-sinks-email#46]
Is there a way to set anonymous credentials for the smtp client? When no network credentials are specified default credentials get used as per lines 147-148 on https://github.com/serilog/serilog-sinks-email/blob/dev/src/Serilog.Sinks.Email/Sinks/Email/EmailSink.cs

**Comment by zee1593** [comment]
I am not sure if my question is the same as the above or of a slightly different flavor.
I have the following setting in my configuration file:
```C#
"WriteTo": [
      {
        "Name": "Email",
        "Args": {
          "fromEmail": "<sender's email address>",
          "toEmail": "<recipient’s email address>",
          "mailServer": "<mail server>",
          "restrictedToMinimumLevel": "Error",
          "mailSubject": "Error",
          "outputTemplate": "<my output template> "
        }
      }
    ],
```
This works just fine on the test and production environments, where port 25 is set up appropriately.

When running the code on my machine during development, I set the sender's and recipient's email address to be my own. 
I would like the code to assume "Default Credentials" when a connection cannot be established on port 25.   This is not possible in the current version of the code.

Is this a reasonable request, or would it break any other requirement?

**Comment by jkiebzak** [comment]
@shoe788 this seems to work for me `NetworkCredentials = new System.Net.NetworkCredential()`

**Comment by Andrei-Astakhov** [comment]
Hi,
The solution provided by @jkiebzak (Thank you!)  works for me, but I guess that it should be an additional parameter that will allow specifying the SmtpClient.UseDefaultCredentials option via App settings. Because with this solution I should use the code to initialize the sink.
