### ISSUE TITLE
Serilog-sinks is not sending email in docker container when error occurs

### ISSUE THREAD

**Issue by liaoqixiang** [serilog/serilog-sinks-email#52]
Log.Logger = new LoggerConfiguration()
                              .WriteTo.Console(restrictedToMinimumLevel: LogEventLevel.Verbose)
                              .WriteTo.Email(new EmailConnectionInfo()
                              {
                                  FromEmail = configuration["Email:fromEmail"],
                                  EmailSubject = configuration["Email:subjectEmail"],
                                  ToEmail = configuration["Email:toEmail"],
                                  MailServer = configuration["Email:mailServer"],
                              },
                            restrictedToMinimumLevel: LogEventLevel.Error)
                            .CreateLogger();

This is my setting. It can send email in local environment but not in docker container. Could anyone have a look to see what is going on?

**Comment by merbla** [comment]
@liaoqixiang initial thoughts relate to network communication being an issue.  How are you addressing your email server (e.g. IP vs DNS)?  What ports have you exposed?

**Comment by liaoqixiang** [comment]
@merbla Hi there, your thought is I haven't set up the port correctly? there is no setting about port in my docker compose file. I guess it is port 80? my email server is smtp server

**Comment by merbla** [comment]
Are you resolving the email server via DNS?

**Comment by liaoqixiang** [comment]
@merbla I think it's IP? It is in my company. I am Junior developer.

**Comment by liaoqixiang** [comment]
@merbla I think I need to check the port tomorrow. Thanks

**Comment by liaoqixiang** [comment]
@merbla I have tried different ports. It seems it's still not working. This web API is using port 80.

**Comment by merbla** [comment]
@liaoqixiang can you try logging to the Serilog console and also use `SelfLog` to expose any errors that might be occurring.

e.g. https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics#selflog

**Comment by merbla** [comment]
@liaoqixiang if you can post an example of the issue that might help working out the details.  My assumption is that it will relate to configuration in Docker.

**Comment by liaoqixiang** [comment]
@merbla 

Here are all the settings.

Docker file:

FROM microsoft/aspnetcore:2.0.6
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENV TZ=NZ
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ /etc/timezone
ENTRYPOINT ["dotnet", "PPPECSInterface.dll"]

Dokcer-compose file:
version: '3.4'

services:
  pppecsinterface:
    image: pppecsinterface
    build:
      context: ./ECS
      dockerfile: Dockerfile


Docker-compose-override:
version: '3.4'

services:
  pppecsinterface:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

Program.cs
 public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
          //  .UseKestrel()
          //  .UseIISIntegration()
                .UseStartup<Startup>()
            //    .UseUrls("http://0.0.0.0:80")
                .UseDefaultServiceProvider(options =>
                  options.ValidateScopes = false)
                .Build();

**Comment by liaoqixiang** [comment]
@merbla I don't see there is a problem of port. It's totally ok if I send email from docker using smtpclient class provided in .net.

**Comment by nblumhardt** [comment]
Closing this one as stale, hope you were able to find a resolution.
