### ISSUE TITLE
Multiline subject fails to send mail

### ISSUE THREAD

**Issue by mgrosperrin** [serilog/serilog-sinks-email#53]
Thanks to #26, we can add {Message} in the subject.
Unfortunately, if {Message} is multiline, the mail will not be send (because subject cannot have multiline).

Is it possible to update the EmailSink to keep only the first line of the subject before sending the email ?

Can help with a PR if needed.

**Comment by adamchester** [comment]
Sounds good @mgrosperrin!

I wonder if it would be better to strip new lines or only keep the first line?
