### ISSUE TITLE
Unreachable mail server for some reason

### ISSUE THREAD

**Issue by irsooti** [serilog/serilog-sinks-email#57]
What is the default behaviour when mail server is unreachable\down? Does it throws an exception wich could potentially stop the app or is handled in same way? Sorry but I didn't find any documentation about that

**Comment by tsimbalar** [comment]
Hi Daniele,

Serilog is designed in such a way that it will never take down your app (see for more details about the philosophy : https://github.com/serilog/serilog/wiki/Reliability ).

If for some reason the e-mail delivery fails, I expect it to write the error to the `SelfLog` which you can read about here : https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics ).

I hope this helps !

**Comment by irsooti** [comment]
Hi @tsimbalar 

Thank you so much, very helpful!
