### ISSUE TITLE
.net45 version send mail after exception

### ISSUE THREAD

**Issue by ste4net** [serilog/serilog-sinks-email#62]
Why not use mailkit for both framework (core and .net45)?

Doing test sending mail (via sendgrid) i recive an exception even if the message is delivered. 

```
2018-10-26T09:11:10.0409337Z Received failed result Error: System.Net.Mail.SmtpException:
Unauthenticated senders not allowe
```

It should be something wrong in authentication type that is correct in mailKit version because using the same configuration with .net Std versione there is no exceptions.
```
c.WriteTo.Email(fromEmail: "..@..",
                toEmail: "..@..",
                mailServer: "smtp.sendgrid.net",
                networkCredential: new System.Net.NetworkCredential("usr", "pwd"),
                mailSubject: "Error",
                restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Error);
```

Although it is not a SmtpClient issue because messages with same parameters are sent with no issue using a System.Net.Mail.SmtpClient too.

**Comment by nblumhardt** [comment]
Closing this one as stale; hope you were able to find a solution.
