### ISSUE TITLE
mailSubject parameter has no effect

### ISSUE THREAD

**Issue by cmeeren** [serilog/serilog-sinks-email#65]
In the `WriteTo.Email` call, the optional `mailSubject` has no effect. It is ignored whether or not `EmailSubject` is provided in the `EmailConnectionInfo` object. If no `EmailSubject` is provided, the subject is simply "Log email", regardless of whether the `mailSubject` is provided in `WriteTo.Email`.

**Comment by nblumhardt** [comment]
3.0.0-dev-* improves the way the configuration methods work (although it's still in need of some polish). Sorry about the lack of response earlier, hope you were able to sort something out. Closing as stale.
