### ISSUE TITLE
batch posting limit is not working when other sink is attached

### ISSUE THREAD

**Issue by danielklecha** [serilog/serilog-sinks-email#66]
Hi,
I created console application with attached code and used smtp4dev as server.
App should send single email but when console sink is attached then I get two emails - with 2 logs and with next 4 logs. When I comment console sink then I get single email.
What is wrong? Is it a bug?
```c#
Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
var emailConnectionInfo = new EmailConnectionInfo
{
    FromEmail = "from@test.com",
    EnableSsl = false,
    EmailSubject = "subject",
    IsBodyHtml = false,
    MailServer = "localhost",
    ToEmail = "to@test.com",
    NetworkCredentials = null,
    Port = 25
};
using (var logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .WriteTo.Email(emailConnectionInfo, batchPostingLimit: 500, restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Warning)
    .CreateLogger())
{
    logger.Information("message");
    logger.Information("message");
    logger.Warning("message");
    logger.Error("message");
    logger.Information("message");
    logger.Information("message");
    logger.Warning("message");
    logger.Error("message");
    logger.Warning("message");
    logger.Warning("message");
}
```

**Comment by campanellaf** [comment]
+1

**Comment by ktodyruik** [comment]
I'm having a similar issue with periodic batching. I'm running some code on an hourly schedule. Error and warning messages should batch and be sent out as one email. It was working at first, batching up the messages in one email, and now it is sending out two emails -- one with each event, even though the events are < 30 seconds apart. When I changed the period to 5 minutes, it sends out two emails 5 minutes apart with log events that occurred seconds apart.

**Comment by ktodyruik** [comment]
Update: I did some testing. There seems to be some side effect related to the "EagerlyEmitFirstEvent" setting in Serilog.Sinks.PeriodicBatching, where the console sink is affecting the period batching of the email sink.

In my case, this test sent out two emails (Warning 1 in the first email, and Waring 2, 3, and 4 in the second):

```csharp
[Fact]
public void EmitFourWarnings()
{
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        // .WriteTo.Console()
        .WriteTo.Email(fromEmail: "Unit Test <noreply@something.com>", toEmail: configuration.SupportEmailAddress, mailServer: configuration.EmailServer, mailSubject: "Testing Periodic Batching", restrictedToMinimumLevel: LogEventLevel.Warning, period: TimeSpan.FromMinutes(5))
        .WriteTo.Console()
        .CreateLogger();
    
    Log.Warning("Warning 1");
    Log.Warning("Warning 2");
    Log.Warning("Warning 3");
    Log.Warning("Warning 4");
    
    Log.CloseAndFlush();
}
```

And this sent out one email:

```csharp
[Fact]
public void EmitFourWarnings()
{
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .WriteTo.Console()
        .WriteTo.Email(fromEmail: "Unit Test <noreply@something.com>", toEmail: configuration.SupportEmailAddress, mailServer: configuration.EmailServer, mailSubject: "Testing Periodic Batching", restrictedToMinimumLevel: LogEventLevel.Warning, period: TimeSpan.FromMinutes(5))
        // .WriteTo.Console()
        .CreateLogger();
    
    Log.Warning("Warning 1");
    Log.Warning("Warning 2");
    Log.Warning("Warning 3");
    Log.Warning("Warning 4");
    
    Log.CloseAndFlush();
}
```

The immediate workaround seems to be either to move the console sink above the email sink, or remove the console sink altogether.

**Comment by nblumhardt** [comment]
Closing this one as stale; I think the batching functionality in this sink is too rudimentary to provide this level of control, currently. Cheers!
