### ISSUE TITLE
Eta on netstandard2.0 support

### ISSUE THREAD

**Issue by rootwalla** [serilog/serilog-sinks-email#67]
No matter the configuration (EnableSSL) we've been unable to get MailKit to communicate with our exchange server. It consistently fails with: "The client and server cannot communicate, because they do not possess a common algorithm". Since we've had no issues when using System.Net.Mail SmtpClient in our Core 2.2 projects, I've been wondering why you guys haven't updated to netstandard2.0.

Related: [#42](https://github.com/serilog/serilog-sinks-email/issues/42)

Any indications on ETA?

If I provide a PR, will it be reviewed/accepted (I ask since other PRs have sat in your queue for over 6 months)?
Also, after a quick look at the source, if a PR were to be provided it would require the project to reference the full NETStandard library, as neither system.net nor system.net.mail are available separately as far as I can tell. Seeing as you've specifically avoided this so far, I am wondering if perhaps this was on purpose vs. simple convenience.

Thank you, Root.

**Comment by balarvs2002** [comment]
any updates ?

**Comment by d668** [comment]
looks dead to me

**Comment by SoulSeekkor** [comment]
Would be nice if this was looked at and updated, just ran into this today.

**Comment by RazorSharpInc** [comment]
It appears the project has been updated to support .NET 4.5, Standard 2.0 and Standard 2.1

**Comment by augustoproiete** [comment]
@RazorSharpInc No stable version released yet:

[![image](https://user-images.githubusercontent.com/177608/84527789-eee07680-acb4-11ea-8522-515971754521.png)](https://github.com/serilog/serilog-sinks-email/releases)

[![image](https://user-images.githubusercontent.com/177608/84527736-d1aba800-acb4-11ea-84a4-c6daaf2eede3.png)](https://www.nuget.org/packages/serilog.sinks.email)

**Comment by arisliang** [comment]
it's surprising to see the last stable version is in 2017, and many pending issue is also from 2017. Is this sink still being actively maintained? Or it's quieting down already.

**Comment by nathanpovo** [comment]
The use of .NETStandard 1.3 also causes the following errors when attempting to publish a project referencing .Net Core 3.0 or higher:

```
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.Primitives 4.0.11 -> runtime.win.System.Net.Primitives 4.3.0 -> System.Collections (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Collections (>= 4.0.11)
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Collections (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Collections (>= 4.0.11)
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.NameResolution (>= 4.0.0)
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.Primitives (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.Primitives (>= 4.0.11)
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.NetworkInformation 4.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Collections (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Collections (>= 4.0.11)
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> Portable.BouncyCastle 1.8.1.1 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Collections (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Collections (>= 4.0.11)
C:\MyProject.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Net.Security 4.0.0 -> System.Security.Cryptography.X509Certificates 4.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Collections (>= 4.3.0)
C:\MyProject.csproj : error NU1605:  MyProject -> Serilog.Sinks.Email 2.3.0 -> MailKit 1.4.2 -> System.Collections (>= 4.0.11)
```

This issue is described [here](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605#example-2).

Updating Serilog.Sinks.Email to [2.4.0-dev-00116](https://www.nuget.org/packages/Serilog.Sinks.Email/2.4.0-dev-00116) solves the issue.

**Comment by andriysavin** [comment]
I have recently faced another related problem. My client is switching to some email relay which doesn't use connection encryption and credentials (it relies on internal network and authentication by IP). In this case, with MailKit implementaion, any value for EnableSsl doesn't make things working, as `true` means `SecureSocketOptions.SslOnConnect`, and `false` means `SecureSocketOptions.StartTlsWhenAvailable`, while the option I need is `SecureSocketOptions.None` (which I have no way to specify). I think this sink should make EnableSsl nullable and obsolete, and introduce and enum similar or the same to `SecureSocketOptions`, which will be exposed via another property, providing full range of options.

**Comment by nblumhardt** [comment]
Closing as stale, 3.0.0-dev-* should have most compat issues sorted. HTH!
