### ISSUE TITLE
Sending too many emails

### ISSUE THREAD

**Issue by josegomez** [serilog/serilog-sinks-email#70]
When executing the below I get several emails sometimes 2 emails sometimes 3. I expcted to get 1 email with all the errors since I specified 100 as the batch limit and there are only 3.

```cs
 Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Console()
                .WriteTo.Email(eml,"{Timestamp:yyyy-MM-dd HH:mm:ss}[{Level}] {Message}{NewLine}{Exception}",Serilog.Events.LogEventLevel.Error,100,null,null,"Customer Interface Log")
                .CreateLogger();
Dictionary<string,Exception> errors = new Dictionary<string,Exception>();
errors.Add("Test", new Exception("Larry");
errors.Add("Test2", new Exception("Larry");
errors.Add("Test3", new Exception("Larry");
foreach(var d in errors)
{
    Log.Error(d.Value, d.Key);
}
Log.CloseAndFlush();
```

**Comment by maxim-melnik** [comment]
I have the same problem. 
It appears in the ASP.NET core app when throw Entity Framework an exception.
First letter comes with Microsoft.EntityFrameworkCore.Database.Command.CommandError, and second with Microsoft.EntityFrameworkCore.Update.SaveChangesFailed.
But actually it is one exception in one web request and they must be packed in one letter.

**Comment by AlesRuzickaEu** [comment]
This sink is in dire need of more functionality (rate control) and mostly documentation.

It's not clear what `batchPostingLimit` means (it's a limit, so it's maximum? how does it work?)

Also how does it work with `period` definition?

**Comment by caioproiete** [comment]
@AlesRuzickaEu Does the [documentation in the XML docs](https://github.com/serilog/serilog-sinks-email/blob/dev/src/Serilog.Sinks.Email/LoggerConfigurationEmailExtensions.cs#L42-L43) help?

```xml
/// <param name="batchPostingLimit">The maximum number of events to post in a single batch.
/// <param name="period">The time to wait between checking for event batches.
```

**Comment by AlesRuzickaEu** [comment]
It's not specific enough for me.

It seems that first error sends email immediately with single entry. After that, period starts and second email is send after `batchPostingLimit` or `period` expires.

I guess that it's difficult with period to start on application start as library does not know when application started - it would know only when it's first called. Current behavior is possibly correct, but should be somehow documented.

**Comment by ktodyruik** [comment]
I'm having a similar issue with periodic batching. I'm running some code on an hourly schedule. Error and warning messages should batch and be sent out as one email. It was working at first, batching up the messages in one email, and now it is sending out two emails -- one with each event, even though the events are < 30 seconds apart. When I changed the period to 5 minutes, it sends out two emails 5 minutes apart with log events that occurred seconds apart.

**Comment by nblumhardt** [comment]
Thanks for all the feedback. The scope of this sink is somewhat limited, but a rate control wrapper could now be implemented using Serilog's `LoggerSinkConfiguration.Wrap()` feature, in case anyone's interested in having a shot?

Closing as stale, but if you decide to give it a go and need some pointers, please feel free to ping me :-)
