### ISSUE TITLE
Can't compile Serilog.Sinks.Email.EmailConnectionInfo

### ISSUE THREAD

**Issue by dpomerantz-msin617** [serilog/serilog-sinks-email#73]
I get this compiler error message when I try to call new Serilog.Sinks.Email.EmailConnectionInfo().
`The type 'EmailConnectionInfo' exists in both 'Serilog.Sinks.Email, Version=2.3.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' and 'Serilog.Sinks.SendGridEmail, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`
I'm not even using Serilog.Sinks.SendGridEmail.

Please advise.
Here's my code:
                    `var emailConnection = new Serilog.Sinks.Email.EmailConnectionInfo()
                    {
                            Port = 587,
                            FromEmail = emailConfig.From,
                            ToEmail = emailConfig.MailTo,
                            NetworkCredentials = new NetworkCredential(emailConfig.User, emailConfig.Password),
                            MailServer = emailConfig.Host
                        };`

**Comment by franky1017** [comment]
Having the same problem, any updates?

**Comment by nblumhardt** [comment]
3.0.0-dev should sort out any remaining TFM specific issues; hope this helps! Closing as stale.
