### ISSUE TITLE
Implement new IBatchedLogEventSink interface

### ISSUE THREAD

**Issue by bcallaghan-et** [serilog/serilog-sinks-email#77]
I propose modifying the EmailSink so that it implements the IBatchedLogEventSink interface rather than deriving from the PeriodicBatching class. Both are from the same package, so no new dependencies are introduced. The introduction of this interface would allow the EmailSink to be used with other batching algorithms, rather than just time-sliced batching. I will volunteer to make this change, if others find it has value.

**Comment by bcallaghan-et** [comment]
My team found it useful, so I started making a prototype that we can use internally, which you can find
[here](https://github.com/Etogy/serilog-sinks-email).

**Comment by nblumhardt** [comment]
Thanks again for raising this; closing as stale.
