### ISSUE TITLE
Skip certificate revocation check

### ISSUE THREAD

**Issue by jamesminchin** [serilog/serilog-sinks-email#79]
I have an application that has no direct internet access. When the email sink sends an email the application hangs for 2 minutes while MailKit attempts to check whether certificates have been revoked.
 
MailKit has a [CheckCertificateRevocation](http://www.mimekit.net/docs/html/P_MailKit_MailService_CheckCertificateRevocation.htm) property which will skip the check. Is there a way to specify this for the email sink, or any workaround?

**Comment by nblumhardt** [comment]
Closing as stale; recent sink versions support this through `EmailConnectionInfo`. HTH!
