### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by intointo312** [serilog/serilog-sinks-email#80]
I am using .Net Core 3.0 and Serilog sends email when tested on localhost but when I push it to server, we are seeing the below error.

The client and server cannot communicate, because they do not possess a common algorithm.

Is there any setting that I need to add/enable?

Thanks!

**Comment by dlausch** [comment]
@intointo312 Can you please post the logic that you used for the localhost working version? Thanks.

**Comment by nblumhardt** [comment]
Closing this one as stale, hope you were able to find a resolution. Cheers!
