### ISSUE TITLE
EagerlyEmitFirstEvent 

### ISSUE THREAD

**Issue by ktodyruik** [serilog/serilog-sinks-email#82]
It appears that in PeriodicBatchingSink, EagerlyEmitFirstEvent defaults to true. And I don't see this being exposed in the EmailSink to change this.

Can anyone comment on this? This is confusing. Would it be possible to change this or expose it so that it can be set to false?

**Comment by 0xced** [comment]
Actually, [`EagerlyEmitFirstEvent` is automatically set to `false`][1] but it's not configurable.

[1]: https://github.com/serilog/serilog-sinks-email/blob/v2.4.0/src/Serilog.Sinks.Email/LoggerConfigurationEmailExtensions.cs#L231

**Comment by nblumhardt** [comment]
The new 3.0.0-dev versions make all batching options configurable. HTH!
