### ISSUE TITLE
Serilog-sinks-email stop working.

### ISSUE THREAD

**Issue by dmta2005** [serilog/serilog-sinks-email#88]
We have been using Serilog email for our .Net Core 2.2 web application projects.   It has been working for months.  But suddenly the email stopped working.   I don't know if anything changed to our environment.  It does not send emails any more.  It still logging the error into the log file.  I have not be able to get it working again.  SMTP email still working in our environment.    Any suggestions to check for our environment.  
Thanks

**Comment by dmta2005** [comment]
We found out the reason the email stopped working because TLS 1.2 was enabled.  Anyone having the same issues with TLS?

**Comment by DavidLpCb** [comment]
We have the same problem since TLS 1.2 was enabled in the server.

**Comment by dmta2005** [comment]
Was you able to resolve the issue?  We have problems with both .Net Core 2.2 & 3.1.  We just use SmtpClient to send email for now.

**Comment by sentjurv** [comment]
Could you please advise, is there any updates? Actually I have the same issue.

**Comment by nblumhardt** [comment]
Closing as stale, 3.0.0-dev-* consistently uses MailKit on all TFMs so may be the thing to try. HTH!
