### ISSUE TITLE
Why does the Email sink not use MailKit on Framework?

### ISSUE THREAD

**Issue by gaazkam** [serilog/serilog-sinks-email#96]
The way I'm getting things is that the Email sink uses the deprecated [`System.Net.Mail.SmtpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient) class if run on Framework and MailKit if run on Core or Standard. This behavior doesn't seem documented and I had to read the source code to find this out.

However, `SmtpClient` is [disrecommended](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.8#remarks) by Microsoft:

>  ### Important
> 
> We don't recommend that you use the `SmtpClien`t class for new development because `SmtpClient` doesn't support many modern protocols. Use [MailKit](https://github.com/jstedfast/MailKit) or other libraries instead. For more information, see [SmtpClient shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md) on GitHub.

In particular, SmtpClient [does not support authenticating against SMTP servers on port 465](https://docs.microsoft.com/en-us/archive/blogs/webdav_101/system-net-mail-with-ssl-to-authenticate-against-port-465). For this reason I was unable to make Serilog.Sinks.Email send emails. MailKit doesn't seem to have this limitation.

Unfortunately, thanks to third party library compatilbility requirements, I'm still stuck on Framework and this is expected to last for about two years. 

Considering that MailKit [does target Framework](https://www.nuget.org/packages/MailKit/) I think it would make sense to use MailKit even on Framework projects. Failing that I think it would make sense to add a configuration option to opt in to the use of MailKit even on Framework. In any case I think that the choice of mailing backends depending on .Net version should be explicitly documented.

**Comment by xantari** [comment]
@gaazkam It does use mailkit, so i'm not sure what you are referencing here. See here: https://github.com/serilog/serilog-sinks-email/blob/dev/src/Serilog.Sinks.Email/Sinks/Email/MailKitEmailTransport.cs

**Comment by nblumhardt** [comment]
3.0.0-dev-* packages now use MailKit and support all options on .NET Framework.
